name = "GitLabCISub1"
uuid = "2df81c4e-c6cd-4631-b325-cacad6d6abac"
authors = ["Simeon Ehrig <s.ehrig@hzdr.de>"]
version = "0.0.1"

[deps]
MonteCarloPI = "2db3c979-7d52-4b64-8d6d-d726b304ac26"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
